# Generated by Django 3.2 on 2023-04-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_full_name',
            field=models.CharField(default='Test User', max_length=50),
            preserve_default=False,
        ),
    ]
